### ISSUE TITLE
Serialization needs a refactor

### ISSUE THREAD

**Issue by playmer** [playmer/YTE#147]
- [ ] Enum Binding

- [ ] Look up serialization functions rather than hardcoding per type.

- [ ] Conversion between Reflected Types

- [ ] Property/Field versioning

- [ ] Consider a Binary Format for publishing

- [ ] Custom Text format

- [ ] Apply Attribute deserialization time from #213
